SELECT
        B_NO,B_NAME,B_AUTHOR,B_PUBLISH
  FROM BOOK152
 WHERE B_NAME LIKE '%'||'ÆÄÀÌ'||'%'; 
 
SELECT
        B_NO,B_NAME,B_AUTHOR,B_PUBLISH
  FROM BOOK152
 WHERE B_AUTHOR LIKE '%'||'¹Ú'||'%'; 
 
SELECT
        B_NO,B_NAME,B_AUTHOR,B_PUBLISH
  FROM BOOK152
 WHERE B_AUTHOR LIKE '%'||:KEYWORD||'%'; 
 
SELECT
        B_NO,B_NAME,B_AUTHOR,B_PUBLISH
  FROM BOOK152
 WHERE B_PUBLISH LIKE '%'||:KEYWORD||'%'; 