SELECT * FROM ZIPCODE_T

SELECT ZIPCODE, ADDRESS
  FROM ZIPCODE_T
WHERE DONG = '신길동';

SELECT ZIPCODE, ADDRESS
  FROM ZIPCODE_T
WHERE DONG LIKE '가산'||'%';

SELECT '전체' ZDO FROM DUAL
UNION ALL
SELECT ZDO 
   FROM (
         SELECT
                DISTINCT(ZDO) ZDO
           FROM ZIPCODE_T
         ORDER BY ZDO ASC
         );

SELECT
        DISTINCT(ZDO) ZDO
    FROM ZIPCODE_T
ORDER BY ZDO DESC;